export default {
    'ab': {
        'itchLocale.alerts.remixing': 'Remixing...',
        'itchLocale.alerts.remixed': 'Successfully remixed.',
        'itchLocale.alerts.savingOriginal': 'Save original project...',
        'itchLocale.alerts.coping': 'Copying...',
        'itchLocale.alerts.successfullyCopied': 'Successfully copied.',
        'itchLocale.cards.lessons': 'Lessons',
        'itchLocale.cards.directions': 'View directions',
        'itchLocale.cards.getAssigment': 'Get Assignment',
        'itchLocale.cards.noLessons': 'No Lessons Available',
        'itchLocale.menuBar.itchLessons': 'Lessons from iTCH',
        'itchLocale.menuBar.projectIsSaving': 'Saving...',
        'itchLocale.menuBar.projectNotSaved': 'Not Saved',
        'itchLocale.menuBar.projectSaved': 'Saved'
    },
    'ar': {
        'itchLocale.alerts.remixing': 'Remixing...',
        'itchLocale.alerts.remixed': 'Successfully remixed.',
        'itchLocale.alerts.savingOriginal': 'Save original project...',
        'itchLocale.alerts.coping': 'Copying...',
        'itchLocale.alerts.successfullyCopied': 'Successfully copied.',
        'itchLocale.cards.lessons': 'Lessons',
        'itchLocale.cards.directions': 'View directions',
        'itchLocale.cards.getAssigment': 'Get Assignment',
        'itchLocale.cards.noLessons': 'No Lessons Available',
        'itchLocale.menuBar.itchLessons': 'Lessons from iTCH',
        'itchLocale.menuBar.projectIsSaving': 'Saving...',
        'itchLocale.menuBar.projectNotSaved': 'Not Saved',
        'itchLocale.menuBar.projectSaved': 'Saved'
    },
    'am': {
        'itchLocale.alerts.remixing': 'Remixing...',
        'itchLocale.alerts.remixed': 'Successfully remixed.',
        'itchLocale.alerts.savingOriginal': 'Save original project...',
        'itchLocale.alerts.coping': 'Copying...',
        'itchLocale.alerts.successfullyCopied': 'Successfully copied.',
        'itchLocale.cards.lessons': 'Lessons',
        'itchLocale.cards.directions': 'View directions',
        'itchLocale.cards.getAssigment': 'Get Assignment',
        'itchLocale.cards.noLessons': 'No Lessons Available',
        'itchLocale.menuBar.itchLessons': 'Lessons from iTCH',
        'itchLocale.menuBar.projectIsSaving': 'Saving...',
        'itchLocale.menuBar.projectNotSaved': 'Not Saved',
        'itchLocale.menuBar.projectSaved': 'Saved'
    },
    'az': {
        'itchLocale.alerts.remixing': 'Remixing...',
        'itchLocale.alerts.remixed': 'Successfully remixed.',
        'itchLocale.alerts.savingOriginal': 'Save original project...',
        'itchLocale.alerts.coping': 'Copying...',
        'itchLocale.alerts.successfullyCopied': 'Successfully copied.',
        'itchLocale.cards.lessons': 'Lessons',
        'itchLocale.cards.directions': 'View directions',
        'itchLocale.cards.getAssigment': 'Get Assignment',
        'itchLocale.cards.noLessons': 'No Lessons Available',
        'itchLocale.menuBar.itchLessons': 'Lessons from iTCH',
        'itchLocale.menuBar.projectIsSaving': 'Saving...',
        'itchLocale.menuBar.projectNotSaved': 'Not Saved',
        'itchLocale.menuBar.projectSaved': 'Saved'
    },
    'id': {
        'itchLocale.alerts.remixing': 'Remixing...',
        'itchLocale.alerts.remixed': 'Successfully remixed.',
        'itchLocale.alerts.savingOriginal': 'Save original project...',
        'itchLocale.alerts.coping': 'Copying...',
        'itchLocale.alerts.successfullyCopied': 'Successfully copied.',
        'itchLocale.cards.lessons': 'Lessons',
        'itchLocale.cards.directions': 'View directions',
        'itchLocale.cards.getAssigment': 'Get Assignment',
        'itchLocale.cards.noLessons': 'No Lessons Available',
        'itchLocale.menuBar.itchLessons': 'Lessons from iTCH',
        'itchLocale.menuBar.projectIsSaving': 'Saving...',
        'itchLocale.menuBar.projectNotSaved': 'Not Saved',
        'itchLocale.menuBar.projectSaved': 'Saved'
    },
    'ca': {
        'itchLocale.alerts.remixing': 'Remixing...',
        'itchLocale.alerts.remixed': 'Successfully remixed.',
        'itchLocale.alerts.savingOriginal': 'Save original project...',
        'itchLocale.alerts.coping': 'Copying...',
        'itchLocale.alerts.successfullyCopied': 'Successfully copied.',
        'itchLocale.cards.lessons': 'Lessons',
        'itchLocale.cards.directions': 'View directions',
        'itchLocale.cards.getAssigment': 'Get Assignment',
        'itchLocale.cards.noLessons': 'No Lessons Available',
        'itchLocale.menuBar.itchLessons': 'Lessons from iTCH',
        'itchLocale.menuBar.projectIsSaving': 'Saving...',
        'itchLocale.menuBar.projectNotSaved': 'Not Saved',
        'itchLocale.menuBar.projectSaved': 'Saved'
    },
    'cs': {
        'itchLocale.alerts.remixing': 'Remixing...',
        'itchLocale.alerts.remixed': 'Successfully remixed.',
        'itchLocale.alerts.savingOriginal': 'Save original project...',
        'itchLocale.alerts.coping': 'Copying...',
        'itchLocale.alerts.successfullyCopied': 'Successfully copied.',
        'itchLocale.cards.lessons': 'Lessons',
        'itchLocale.cards.directions': 'View directions',
        'itchLocale.cards.getAssigment': 'Get Assignment',
        'itchLocale.cards.noLessons': 'No Lessons Available',
        'itchLocale.menuBar.itchLessons': 'Lessons from iTCH',
        'itchLocale.menuBar.projectIsSaving': 'Saving...',
        'itchLocale.menuBar.projectNotSaved': 'Not Saved',
        'itchLocale.menuBar.projectSaved': 'Saved'
    },
    'cy': {
        'itchLocale.alerts.remixing': 'Remixing...',
        'itchLocale.alerts.remixed': 'Successfully remixed.',
        'itchLocale.alerts.savingOriginal': 'Save original project...',
        'itchLocale.alerts.coping': 'Copying...',
        'itchLocale.alerts.successfullyCopied': 'Successfully copied.',
        'itchLocale.cards.lessons': 'Lessons',
        'itchLocale.cards.directions': 'View directions',
        'itchLocale.cards.getAssigment': 'Get Assignment',
        'itchLocale.cards.noLessons': 'No Lessons Available',
        'itchLocale.menuBar.itchLessons': 'Lessons from iTCH',
        'itchLocale.menuBar.projectIsSaving': 'Saving...',
        'itchLocale.menuBar.projectNotSaved': 'Not Saved',
        'itchLocale.menuBar.projectSaved': 'Saved'
    },
    'da': {
        'itchLocale.alerts.remixing': 'Remixing...',
        'itchLocale.alerts.remixed': 'Successfully remixed.',
        'itchLocale.alerts.savingOriginal': 'Save original project...',
        'itchLocale.alerts.coping': 'Copying...',
        'itchLocale.alerts.successfullyCopied': 'Successfully copied.',
        'itchLocale.cards.lessons': 'Lessons',
        'itchLocale.cards.directions': 'View directions',
        'itchLocale.cards.getAssigment': 'Get Assignment',
        'itchLocale.cards.noLessons': 'No Lessons Available',
        'itchLocale.menuBar.itchLessons': 'Lessons from iTCH',
        'itchLocale.menuBar.projectIsSaving': 'Saving...',
        'itchLocale.menuBar.projectNotSaved': 'Not Saved',
        'itchLocale.menuBar.projectSaved': 'Saved'
    },
    'de': {
        'itchLocale.alerts.remixing': 'Remixing...',
        'itchLocale.alerts.remixed': 'Successfully remixed.',
        'itchLocale.alerts.savingOriginal': 'Save original project...',
        'itchLocale.alerts.coping': 'Copying...',
        'itchLocale.alerts.successfullyCopied': 'Successfully copied.',
        'itchLocale.cards.lessons': 'Lessons',
        'itchLocale.cards.directions': 'View directions',
        'itchLocale.cards.getAssigment': 'Get Assignment',
        'itchLocale.cards.noLessons': 'No Lessons Available',
        'itchLocale.menuBar.itchLessons': 'Lessons from iTCH',
        'itchLocale.menuBar.projectIsSaving': 'Saving...',
        'itchLocale.menuBar.projectNotSaved': 'Not Saved',
        'itchLocale.menuBar.projectSaved': 'Saved'
    },
    'et': {
        'itchLocale.alerts.remixing': 'Remixing...',
        'itchLocale.alerts.remixed': 'Successfully remixed.',
        'itchLocale.alerts.savingOriginal': 'Save original project...',
        'itchLocale.alerts.coping': 'Copying...',
        'itchLocale.alerts.successfullyCopied': 'Successfully copied.',
        'itchLocale.cards.lessons': 'Lessons',
        'itchLocale.cards.directions': 'View directions',
        'itchLocale.cards.getAssigment': 'Get Assignment',
        'itchLocale.cards.noLessons': 'No Lessons Available',
        'itchLocale.menuBar.itchLessons': 'Lessons from iTCH',
        'itchLocale.menuBar.projectIsSaving': 'Saving...',
        'itchLocale.menuBar.projectNotSaved': 'Not Saved',
        'itchLocale.menuBar.projectSaved': 'Saved'
    },
    'el': {
        'itchLocale.alerts.remixing': 'Remixing...',
        'itchLocale.alerts.remixed': 'Successfully remixed.',
        'itchLocale.alerts.savingOriginal': 'Save original project...',
        'itchLocale.alerts.coping': 'Copying...',
        'itchLocale.alerts.successfullyCopied': 'Successfully copied.',
        'itchLocale.cards.lessons': 'Lessons',
        'itchLocale.cards.directions': 'View directions',
        'itchLocale.cards.getAssigment': 'Get Assignment',
        'itchLocale.cards.noLessons': 'No Lessons Available',
        'itchLocale.menuBar.itchLessons': 'Lessons from iTCH',
        'itchLocale.menuBar.projectIsSaving': 'Saving...',
        'itchLocale.menuBar.projectNotSaved': 'Not Saved',
        'itchLocale.menuBar.projectSaved': 'Saved'
    },
    'en': {
        'itchLocale.alerts.remixing': 'Remixing...',
        'itchLocale.alerts.remixed': 'Successfully remixed.',
        'itchLocale.alerts.savingOriginal': 'Save original project...',
        'itchLocale.alerts.coping': 'Copying...',
        'itchLocale.alerts.successfullyCopied': 'Successfully copied.',
        'itchLocale.cards.lessons': 'Lessons',
        'itchLocale.cards.directions': 'View directions',
        'itchLocale.cards.getAssigment': 'Get Assignment',
        'itchLocale.cards.noLessons': 'No Lessons Available',
        'itchLocale.menuBar.itchLessons': 'Lessons from iTCH',
        'itchLocale.menuBar.projectIsSaving': 'Saving...',
        'itchLocale.menuBar.projectNotSaved': 'Not Saved',
        'itchLocale.menuBar.projectSaved': 'Saved'
    },
    'es': {
        'itchLocale.alerts.remixing': 'Mezclando...',
        'itchLocale.alerts.remixed': 'Mezclado exitosamente.',
        'itchLocale.alerts.savingOriginal': 'Guardar proyecto original...',
        'itchLocale.alerts.coping': 'Copiando...',
        'itchLocale.alerts.successfullyCopied': 'Copiado exitosamente.',
        'itchLocale.cards.lessons': 'Lecciones',
        'itchLocale.cards.directions': 'Ver direcciones',
        'itchLocale.cards.getAssigment': 'Obtener Tarea',
        'itchLocale.cards.noLessons': 'No hay lección disponible',
        'itchLocale.menuBar.itchLessons': 'Lección de iTCH',
        'itchLocale.menuBar.projectIsSaving': 'Guardando...',
        'itchLocale.menuBar.projectNotSaved': 'No guardado',
        'itchLocale.menuBar.projectSaved': 'Guardado'
    },
    'es-419': {
        'itchLocale.alerts.remixing': 'Remixing...',
        'itchLocale.alerts.remixed': 'Successfully remixed.',
        'itchLocale.alerts.savingOriginal': 'Save original project...',
        'itchLocale.alerts.coping': 'Copying...',
        'itchLocale.alerts.successfullyCopied': 'Successfully copied.',
        'itchLocale.cards.lessons': 'Lessons',
        'itchLocale.cards.directions': 'View directions',
        'itchLocale.cards.getAssigment': 'Get Assignment',
        'itchLocale.cards.noLessons': 'No Lessons Available',
        'itchLocale.menuBar.itchLessons': 'Lessons from iTCH',
        'itchLocale.menuBar.projectIsSaving': 'Saving...',
        'itchLocale.menuBar.projectNotSaved': 'Not Saved',
        'itchLocale.menuBar.projectSaved': 'Saved'
    },
    'eu': {
        'itchLocale.alerts.remixing': 'Remixing...',
        'itchLocale.alerts.remixed': 'Successfully remixed.',
        'itchLocale.alerts.savingOriginal': 'Save original project...',
        'itchLocale.alerts.coping': 'Copying...',
        'itchLocale.alerts.successfullyCopied': 'Successfully copied.',
        'itchLocale.cards.lessons': 'Lessons',
        'itchLocale.cards.directions': 'View directions',
        'itchLocale.cards.getAssigment': 'Get Assignment',
        'itchLocale.cards.noLessons': 'No Lessons Available',
        'itchLocale.menuBar.itchLessons': 'Lessons from iTCH',
        'itchLocale.menuBar.projectIsSaving': 'Saving...',
        'itchLocale.menuBar.projectNotSaved': 'Not Saved',
        'itchLocale.menuBar.projectSaved': 'Saved'
    },
    'fr': {
        'itchLocale.alerts.remixing': 'Remixing...',
        'itchLocale.alerts.remixed': 'Successfully remixed.',
        'itchLocale.alerts.savingOriginal': 'Save original project...',
        'itchLocale.alerts.coping': 'Copying...',
        'itchLocale.alerts.successfullyCopied': 'Successfully copied.',
        'itchLocale.cards.lessons': 'Lessons',
        'itchLocale.cards.directions': 'View directions',
        'itchLocale.cards.getAssigment': 'Get Assignment',
        'itchLocale.cards.noLessons': 'No Lessons Available',
        'itchLocale.menuBar.itchLessons': 'Lessons from iTCH',
        'itchLocale.menuBar.projectIsSaving': 'Saving...',
        'itchLocale.menuBar.projectNotSaved': 'Not Saved',
        'itchLocale.menuBar.projectSaved': 'Saved'
    },
    'ga': {
        'itchLocale.alerts.remixing': 'Remixing...',
        'itchLocale.alerts.remixed': 'Successfully remixed.',
        'itchLocale.alerts.savingOriginal': 'Save original project...',
        'itchLocale.alerts.coping': 'Copying...',
        'itchLocale.alerts.successfullyCopied': 'Successfully copied.',
        'itchLocale.cards.lessons': 'Lessons',
        'itchLocale.cards.directions': 'View directions',
        'itchLocale.cards.getAssigment': 'Get Assignment',
        'itchLocale.cards.noLessons': 'No Lessons Available',
        'itchLocale.menuBar.itchLessons': 'Lessons from iTCH',
        'itchLocale.menuBar.projectIsSaving': 'Saving...',
        'itchLocale.menuBar.projectNotSaved': 'Not Saved',
        'itchLocale.menuBar.projectSaved': 'Saved'
    },
    'gd': {
        'itchLocale.alerts.remixing': 'Remixing...',
        'itchLocale.alerts.remixed': 'Successfully remixed.',
        'itchLocale.alerts.savingOriginal': 'Save original project...',
        'itchLocale.alerts.coping': 'Copying...',
        'itchLocale.alerts.successfullyCopied': 'Successfully copied.',
        'itchLocale.cards.lessons': 'Lessons',
        'itchLocale.cards.directions': 'View directions',
        'itchLocale.cards.getAssigment': 'Get Assignment',
        'itchLocale.cards.noLessons': 'No Lessons Available',
        'itchLocale.menuBar.itchLessons': 'Lessons from iTCH',
        'itchLocale.menuBar.projectIsSaving': 'Saving...',
        'itchLocale.menuBar.projectNotSaved': 'Not Saved',
        'itchLocale.menuBar.projectSaved': 'Saved'
    },
    'gl': {
        'itchLocale.alerts.remixing': 'Remixing...',
        'itchLocale.alerts.remixed': 'Successfully remixed.',
        'itchLocale.alerts.savingOriginal': 'Save original project...',
        'itchLocale.alerts.coping': 'Copying...',
        'itchLocale.alerts.successfullyCopied': 'Successfully copied.',
        'itchLocale.cards.lessons': 'Lessons',
        'itchLocale.cards.directions': 'View directions',
        'itchLocale.cards.getAssigment': 'Get Assignment',
        'itchLocale.cards.noLessons': 'No Lessons Available',
        'itchLocale.menuBar.itchLessons': 'Lessons from iTCH',
        'itchLocale.menuBar.projectIsSaving': 'Saving...',
        'itchLocale.menuBar.projectNotSaved': 'Not Saved',
        'itchLocale.menuBar.projectSaved': 'Saved'
    },
    'ko': {
        'itchLocale.alerts.remixing': 'Remixing...',
        'itchLocale.alerts.remixed': 'Successfully remixed.',
        'itchLocale.alerts.savingOriginal': 'Save original project...',
        'itchLocale.alerts.coping': 'Copying...',
        'itchLocale.alerts.successfullyCopied': 'Successfully copied.',
        'itchLocale.cards.lessons': 'Lessons',
        'itchLocale.cards.directions': 'View directions',
        'itchLocale.cards.getAssigment': 'Get Assignment',
        'itchLocale.cards.noLessons': 'No Lessons Available',
        'itchLocale.menuBar.itchLessons': 'Lessons from iTCH',
        'itchLocale.menuBar.projectIsSaving': 'Saving...',
        'itchLocale.menuBar.projectNotSaved': 'Not Saved',
        'itchLocale.menuBar.projectSaved': 'Saved'
    },
    'he': {
        'itchLocale.alerts.remixing': 'Remixing...',
        'itchLocale.alerts.remixed': 'Successfully remixed.',
        'itchLocale.alerts.savingOriginal': 'Save original project...',
        'itchLocale.alerts.coping': 'Copying...',
        'itchLocale.alerts.successfullyCopied': 'Successfully copied.',
        'itchLocale.cards.lessons': 'Lessons',
        'itchLocale.cards.directions': 'View directions',
        'itchLocale.cards.getAssigment': 'Get Assignment',
        'itchLocale.cards.noLessons': 'No Lessons Available',
        'itchLocale.menuBar.itchLessons': 'Lessons from iTCH',
        'itchLocale.menuBar.projectIsSaving': 'Saving...',
        'itchLocale.menuBar.projectNotSaved': 'Not Saved',
        'itchLocale.menuBar.projectSaved': 'Saved'
    },
    'is': {
        'itchLocale.alerts.remixing': 'Remixing...',
        'itchLocale.alerts.remixed': 'Successfully remixed.',
        'itchLocale.alerts.savingOriginal': 'Save original project...',
        'itchLocale.alerts.coping': 'Copying...',
        'itchLocale.alerts.successfullyCopied': 'Successfully copied.',
        'itchLocale.cards.lessons': 'Lessons',
        'itchLocale.cards.directions': 'View directions',
        'itchLocale.cards.getAssigment': 'Get Assignment',
        'itchLocale.cards.noLessons': 'No Lessons Available',
        'itchLocale.menuBar.itchLessons': 'Lessons from iTCH',
        'itchLocale.menuBar.projectIsSaving': 'Saving...',
        'itchLocale.menuBar.projectNotSaved': 'Not Saved',
        'itchLocale.menuBar.projectSaved': 'Saved'
    },
    'it': {
        'itchLocale.alerts.remixing': 'Remixing...',
        'itchLocale.alerts.remixed': 'Successfully remixed.',
        'itchLocale.alerts.savingOriginal': 'Save original project...',
        'itchLocale.alerts.coping': 'Copying...',
        'itchLocale.alerts.successfullyCopied': 'Successfully copied.',
        'itchLocale.cards.lessons': 'Lessons',
        'itchLocale.cards.directions': 'View directions',
        'itchLocale.cards.getAssigment': 'Get Assignment',
        'itchLocale.cards.noLessons': 'No Lessons Available',
        'itchLocale.menuBar.itchLessons': 'Lessons from iTCH',
        'itchLocale.menuBar.projectIsSaving': 'Saving...',
        'itchLocale.menuBar.projectNotSaved': 'Not Saved',
        'itchLocale.menuBar.projectSaved': 'Saved'
    },
    'lv': {
        'itchLocale.alerts.remixing': 'Remixing...',
        'itchLocale.alerts.remixed': 'Successfully remixed.',
        'itchLocale.alerts.savingOriginal': 'Save original project...',
        'itchLocale.alerts.coping': 'Copying...',
        'itchLocale.alerts.successfullyCopied': 'Successfully copied.',
        'itchLocale.cards.lessons': 'Lessons',
        'itchLocale.cards.directions': 'View directions',
        'itchLocale.cards.getAssigment': 'Get Assignment',
        'itchLocale.cards.noLessons': 'No Lessons Available',
        'itchLocale.menuBar.itchLessons': 'Lessons from iTCH',
        'itchLocale.menuBar.projectIsSaving': 'Saving...',
        'itchLocale.menuBar.projectNotSaved': 'Not Saved',
        'itchLocale.menuBar.projectSaved': 'Saved'
    },
    'lt': {
        'itchLocale.alerts.remixing': 'Remixing...',
        'itchLocale.alerts.remixed': 'Successfully remixed.',
        'itchLocale.alerts.savingOriginal': 'Save original project...',
        'itchLocale.alerts.coping': 'Copying...',
        'itchLocale.alerts.successfullyCopied': 'Successfully copied.',
        'itchLocale.cards.lessons': 'Lessons',
        'itchLocale.cards.directions': 'View directions',
        'itchLocale.cards.getAssigment': 'Get Assignment',
        'itchLocale.cards.noLessons': 'No Lessons Available',
        'itchLocale.menuBar.itchLessons': 'Lessons from iTCH',
        'itchLocale.menuBar.projectIsSaving': 'Saving...',
        'itchLocale.menuBar.projectNotSaved': 'Not Saved',
        'itchLocale.menuBar.projectSaved': 'Saved'
    },
    'mi': {
        'itchLocale.alerts.remixing': 'Remixing...',
        'itchLocale.alerts.remixed': 'Successfully remixed.',
        'itchLocale.alerts.savingOriginal': 'Save original project...',
        'itchLocale.alerts.coping': 'Copying...',
        'itchLocale.alerts.successfullyCopied': 'Successfully copied.',
        'itchLocale.cards.lessons': 'Lessons',
        'itchLocale.cards.directions': 'View directions',
        'itchLocale.cards.getAssigment': 'Get Assignment',
        'itchLocale.cards.noLessons': 'No Lessons Available',
        'itchLocale.menuBar.itchLessons': 'Lessons from iTCH',
        'itchLocale.menuBar.projectIsSaving': 'Saving...',
        'itchLocale.menuBar.projectNotSaved': 'Not Saved',
        'itchLocale.menuBar.projectSaved': 'Saved'
    },
    'nl': {
        'itchLocale.alerts.remixing': 'Remixing...',
        'itchLocale.alerts.remixed': 'Successfully remixed.',
        'itchLocale.alerts.savingOriginal': 'Save original project...',
        'itchLocale.alerts.coping': 'Copying...',
        'itchLocale.alerts.successfullyCopied': 'Successfully copied.',
        'itchLocale.cards.lessons': 'Lessons',
        'itchLocale.cards.directions': 'View directions',
        'itchLocale.cards.getAssigment': 'Get Assignment',
        'itchLocale.cards.noLessons': 'No Lessons Available',
        'itchLocale.menuBar.itchLessons': 'Lessons from iTCH',
        'itchLocale.menuBar.projectIsSaving': 'Saving...',
        'itchLocale.menuBar.projectNotSaved': 'Not Saved',
        'itchLocale.menuBar.projectSaved': 'Saved'
    },
    'ja': {
        'itchLocale.alerts.remixing': 'Remixing...',
        'itchLocale.alerts.remixed': 'Successfully remixed.',
        'itchLocale.alerts.savingOriginal': 'Save original project...',
        'itchLocale.alerts.coping': 'Copying...',
        'itchLocale.alerts.successfullyCopied': 'Successfully copied.',
        'itchLocale.cards.lessons': 'Lessons',
        'itchLocale.cards.directions': 'View directions',
        'itchLocale.cards.getAssigment': 'Get Assignment',
        'itchLocale.cards.noLessons': 'No Lessons Available',
        'itchLocale.menuBar.itchLessons': 'Lessons from iTCH',
        'itchLocale.menuBar.projectIsSaving': 'Saving...',
        'itchLocale.menuBar.projectNotSaved': 'Not Saved',
        'itchLocale.menuBar.projectSaved': 'Saved'
    },
    'ja-Hira': {
        'itchLocale.alerts.remixing': 'Remixing...',
        'itchLocale.alerts.remixed': 'Successfully remixed.',
        'itchLocale.alerts.savingOriginal': 'Save original project...',
        'itchLocale.alerts.coping': 'Copying...',
        'itchLocale.alerts.successfullyCopied': 'Successfully copied.',
        'itchLocale.cards.lessons': 'Lessons',
        'itchLocale.cards.directions': 'View directions',
        'itchLocale.cards.getAssigment': 'Get Assignment',
        'itchLocale.cards.noLessons': 'No Lessons Available',
        'itchLocale.menuBar.itchLessons': 'Lessons from iTCH',
        'itchLocale.menuBar.projectIsSaving': 'Saving...',
        'itchLocale.menuBar.projectNotSaved': 'Not Saved',
        'itchLocale.menuBar.projectSaved': 'Saved'
    },
    'hu': {
        'itchLocale.alerts.remixing': 'Remixing...',
        'itchLocale.alerts.remixed': 'Successfully remixed.',
        'itchLocale.alerts.savingOriginal': 'Save original project...',
        'itchLocale.alerts.coping': 'Copying...',
        'itchLocale.alerts.successfullyCopied': 'Successfully copied.',
        'itchLocale.cards.lessons': 'Lessons',
        'itchLocale.cards.directions': 'View directions',
        'itchLocale.cards.getAssigment': 'Get Assignment',
        'itchLocale.cards.noLessons': 'No Lessons Available',
        'itchLocale.menuBar.itchLessons': 'Lessons from iTCH',
        'itchLocale.menuBar.projectIsSaving': 'Saving...',
        'itchLocale.menuBar.projectNotSaved': 'Not Saved',
        'itchLocale.menuBar.projectSaved': 'Saved'
    },
    'nb': {
        'itchLocale.alerts.remixing': 'Remixing...',
        'itchLocale.alerts.remixed': 'Successfully remixed.',
        'itchLocale.alerts.savingOriginal': 'Save original project...',
        'itchLocale.alerts.coping': 'Copying...',
        'itchLocale.alerts.successfullyCopied': 'Successfully copied.',
        'itchLocale.cards.lessons': 'Lessons',
        'itchLocale.cards.directions': 'View directions',
        'itchLocale.cards.getAssigment': 'Get Assignment',
        'itchLocale.cards.noLessons': 'No Lessons Available',
        'itchLocale.menuBar.itchLessons': 'Lessons from iTCH',
        'itchLocale.menuBar.projectIsSaving': 'Saving...',
        'itchLocale.menuBar.projectNotSaved': 'Not Saved',
        'itchLocale.menuBar.projectSaved': 'Saved'
    },
    'nn': {
        'itchLocale.alerts.remixing': 'Remixing...',
        'itchLocale.alerts.remixed': 'Successfully remixed.',
        'itchLocale.alerts.savingOriginal': 'Save original project...',
        'itchLocale.alerts.coping': 'Copying...',
        'itchLocale.alerts.successfullyCopied': 'Successfully copied.',
        'itchLocale.cards.lessons': 'Lessons',
        'itchLocale.cards.directions': 'View directions',
        'itchLocale.cards.getAssigment': 'Get Assignment',
        'itchLocale.cards.noLessons': 'No Lessons Available',
        'itchLocale.menuBar.itchLessons': 'Lessons from iTCH',
        'itchLocale.menuBar.projectIsSaving': 'Saving...',
        'itchLocale.menuBar.projectNotSaved': 'Not Saved',
        'itchLocale.menuBar.projectSaved': 'Saved'
    },
    'th': {
        'itchLocale.alerts.remixing': 'Remixing...',
        'itchLocale.alerts.remixed': 'Successfully remixed.',
        'itchLocale.alerts.savingOriginal': 'Save original project...',
        'itchLocale.alerts.coping': 'Copying...',
        'itchLocale.alerts.successfullyCopied': 'Successfully copied.',
        'itchLocale.cards.lessons': 'Lessons',
        'itchLocale.cards.directions': 'View directions',
        'itchLocale.cards.getAssigment': 'Get Assignment',
        'itchLocale.cards.noLessons': 'No Lessons Available',
        'itchLocale.menuBar.itchLessons': 'Lessons from iTCH',
        'itchLocale.menuBar.projectIsSaving': 'Saving...',
        'itchLocale.menuBar.projectNotSaved': 'Not Saved',
        'itchLocale.menuBar.projectSaved': 'Saved'
    },
    'pl': {
        'itchLocale.alerts.remixing': 'Remixing...',
        'itchLocale.alerts.remixed': 'Successfully remixed.',
        'itchLocale.alerts.savingOriginal': 'Save original project...',
        'itchLocale.alerts.coping': 'Copying...',
        'itchLocale.alerts.successfullyCopied': 'Successfully copied.',
        'itchLocale.cards.lessons': 'Lessons',
        'itchLocale.cards.directions': 'View directions',
        'itchLocale.cards.getAssigment': 'Get Assignment',
        'itchLocale.cards.noLessons': 'No Lessons Available',
        'itchLocale.menuBar.itchLessons': 'Lessons from iTCH',
        'itchLocale.menuBar.projectIsSaving': 'Saving...',
        'itchLocale.menuBar.projectNotSaved': 'Not Saved',
        'itchLocale.menuBar.projectSaved': 'Saved'
    },
    'pt': {
        'itchLocale.alerts.remixing': 'Remixing...',
        'itchLocale.alerts.remixed': 'Successfully remixed.',
        'itchLocale.alerts.savingOriginal': 'Save original project...',
        'itchLocale.alerts.coping': 'Copying...',
        'itchLocale.alerts.successfullyCopied': 'Successfully copied.',
        'itchLocale.cards.lessons': 'Lessons',
        'itchLocale.cards.directions': 'View directions',
        'itchLocale.cards.getAssigment': 'Get Assignment',
        'itchLocale.cards.noLessons': 'No Lessons Available',
        'itchLocale.menuBar.itchLessons': 'Lessons from iTCH',
        'itchLocale.menuBar.projectIsSaving': 'Saving...',
        'itchLocale.menuBar.projectNotSaved': 'Not Saved',
        'itchLocale.menuBar.projectSaved': 'Saved'
    },
    'pt-br': {
        'itchLocale.alerts.remixing': 'Remixing...',
        'itchLocale.alerts.remixed': 'Successfully remixed.',
        'itchLocale.alerts.savingOriginal': 'Save original project...',
        'itchLocale.alerts.coping': 'Copying...',
        'itchLocale.alerts.successfullyCopied': 'Successfully copied.',
        'itchLocale.cards.lessons': 'Lessons',
        'itchLocale.cards.directions': 'View directions',
        'itchLocale.cards.getAssigment': 'Get Assignment',
        'itchLocale.cards.noLessons': 'No Lessons Available',
        'itchLocale.menuBar.itchLessons': 'Lessons from iTCH',
        'itchLocale.menuBar.projectIsSaving': 'Saving...',
        'itchLocale.menuBar.projectNotSaved': 'Not Saved',
        'itchLocale.menuBar.projectSaved': 'Saved'
    },
    'ro': {
        'itchLocale.alerts.remixing': 'Remixing...',
        'itchLocale.alerts.remixed': 'Successfully remixed.',
        'itchLocale.alerts.savingOriginal': 'Save original project...',
        'itchLocale.alerts.coping': 'Copying...',
        'itchLocale.alerts.successfullyCopied': 'Successfully copied.',
        'itchLocale.cards.lessons': 'Lessons',
        'itchLocale.cards.directions': 'View directions',
        'itchLocale.cards.getAssigment': 'Get Assignment',
        'itchLocale.cards.noLessons': 'No Lessons Available',
        'itchLocale.menuBar.itchLessons': 'Lessons from iTCH',
        'itchLocale.menuBar.projectIsSaving': 'Saving...',
        'itchLocale.menuBar.projectNotSaved': 'Not Saved',
        'itchLocale.menuBar.projectSaved': 'Saved'
    },
    'ru': {
        'itchLocale.alerts.remixing': 'Remixing...',
        'itchLocale.alerts.remixed': 'Successfully remixed.',
        'itchLocale.alerts.savingOriginal': 'Save original project...',
        'itchLocale.alerts.coping': 'Copying...',
        'itchLocale.alerts.successfullyCopied': 'Successfully copied.',
        'itchLocale.cards.lessons': 'Lessons',
        'itchLocale.cards.directions': 'View directions',
        'itchLocale.cards.getAssigment': 'Get Assignment',
        'itchLocale.cards.noLessons': 'No Lessons Available',
        'itchLocale.menuBar.itchLessons': 'Lessons from iTCH',
        'itchLocale.menuBar.projectIsSaving': 'Saving...',
        'itchLocale.menuBar.projectNotSaved': 'Not Saved',
        'itchLocale.menuBar.projectSaved': 'Saved'
    },
    'sr': {
        'itchLocale.alerts.remixing': 'Remixing...',
        'itchLocale.alerts.remixed': 'Successfully remixed.',
        'itchLocale.alerts.savingOriginal': 'Save original project...',
        'itchLocale.alerts.coping': 'Copying...',
        'itchLocale.alerts.successfullyCopied': 'Successfully copied.',
        'itchLocale.cards.lessons': 'Lessons',
        'itchLocale.cards.directions': 'View directions',
        'itchLocale.cards.getAssigment': 'Get Assignment',
        'itchLocale.cards.noLessons': 'No Lessons Available',
        'itchLocale.menuBar.itchLessons': 'Lessons from iTCH',
        'itchLocale.menuBar.projectIsSaving': 'Saving...',
        'itchLocale.menuBar.projectNotSaved': 'Not Saved',
        'itchLocale.menuBar.projectSaved': 'Saved'
    },
    'sk': {
        'itchLocale.alerts.remixing': 'Remixing...',
        'itchLocale.alerts.remixed': 'Successfully remixed.',
        'itchLocale.alerts.savingOriginal': 'Save original project...',
        'itchLocale.alerts.coping': 'Copying...',
        'itchLocale.alerts.successfullyCopied': 'Successfully copied.',
        'itchLocale.cards.lessons': 'Lessons',
        'itchLocale.cards.directions': 'View directions',
        'itchLocale.cards.getAssigment': 'Get Assignment',
        'itchLocale.cards.noLessons': 'No Lessons Available',
        'itchLocale.menuBar.itchLessons': 'Lessons from iTCH',
        'itchLocale.menuBar.projectIsSaving': 'Saving...',
        'itchLocale.menuBar.projectNotSaved': 'Not Saved',
        'itchLocale.menuBar.projectSaved': 'Saved'
    },
    'sl': {
        'itchLocale.alerts.remixing': 'Remixing...',
        'itchLocale.alerts.remixed': 'Successfully remixed.',
        'itchLocale.alerts.savingOriginal': 'Save original project...',
        'itchLocale.alerts.coping': 'Copying...',
        'itchLocale.alerts.successfullyCopied': 'Successfully copied.',
        'itchLocale.cards.lessons': 'Lessons',
        'itchLocale.cards.directions': 'View directions',
        'itchLocale.cards.getAssigment': 'Get Assignment',
        'itchLocale.cards.noLessons': 'No Lessons Available',
        'itchLocale.menuBar.itchLessons': 'Lessons from iTCH',
        'itchLocale.menuBar.projectIsSaving': 'Saving...',
        'itchLocale.menuBar.projectNotSaved': 'Not Saved',
        'itchLocale.menuBar.projectSaved': 'Saved'
    },
    'fi': {
        'itchLocale.alerts.remixing': 'Remixing...',
        'itchLocale.alerts.remixed': 'Successfully remixed.',
        'itchLocale.alerts.savingOriginal': 'Save original project...',
        'itchLocale.alerts.coping': 'Copying...',
        'itchLocale.alerts.successfullyCopied': 'Successfully copied.',
        'itchLocale.cards.lessons': 'Lessons',
        'itchLocale.cards.directions': 'View directions',
        'itchLocale.cards.getAssigment': 'Get Assignment',
        'itchLocale.cards.noLessons': 'No Lessons Available',
        'itchLocale.menuBar.itchLessons': 'Lessons from iTCH',
        'itchLocale.menuBar.projectIsSaving': 'Saving...',
        'itchLocale.menuBar.projectNotSaved': 'Not Saved',
        'itchLocale.menuBar.projectSaved': 'Saved'
    },
    'sv': {
        'itchLocale.alerts.remixing': 'Remixing...',
        'itchLocale.alerts.remixed': 'Successfully remixed.',
        'itchLocale.alerts.savingOriginal': 'Save original project...',
        'itchLocale.alerts.coping': 'Copying...',
        'itchLocale.alerts.successfullyCopied': 'Successfully copied.',
        'itchLocale.cards.lessons': 'Lessons',
        'itchLocale.cards.directions': 'View directions',
        'itchLocale.cards.getAssigment': 'Get Assignment',
        'itchLocale.cards.noLessons': 'No Lessons Available',
        'itchLocale.menuBar.itchLessons': 'Lessons from iTCH',
        'itchLocale.menuBar.projectIsSaving': 'Saving...',
        'itchLocale.menuBar.projectNotSaved': 'Not Saved',
        'itchLocale.menuBar.projectSaved': 'Saved'
    },
    'vi': {
        'itchLocale.alerts.remixing': 'Remixing...',
        'itchLocale.alerts.remixed': 'Successfully remixed.',
        'itchLocale.alerts.savingOriginal': 'Save original project...',
        'itchLocale.alerts.coping': 'Copying...',
        'itchLocale.alerts.successfullyCopied': 'Successfully copied.',
        'itchLocale.cards.lessons': 'Lessons',
        'itchLocale.cards.directions': 'View directions',
        'itchLocale.cards.getAssigment': 'Get Assignment',
        'itchLocale.cards.noLessons': 'No Lessons Available',
        'itchLocale.menuBar.itchLessons': 'Lessons from iTCH',
        'itchLocale.menuBar.projectIsSaving': 'Saving...',
        'itchLocale.menuBar.projectNotSaved': 'Not Saved',
        'itchLocale.menuBar.projectSaved': 'Saved'
    },
    'tr': {
        'itchLocale.alerts.remixing': 'Remixing...',
        'itchLocale.alerts.remixed': 'Successfully remixed.',
        'itchLocale.alerts.savingOriginal': 'Save original project...',
        'itchLocale.alerts.coping': 'Copying...',
        'itchLocale.alerts.successfullyCopied': 'Successfully copied.',
        'itchLocale.cards.lessons': 'Lessons',
        'itchLocale.cards.directions': 'View directions',
        'itchLocale.cards.getAssigment': 'Get Assignment',
        'itchLocale.cards.noLessons': 'No Lessons Available',
        'itchLocale.menuBar.itchLessons': 'Lessons from iTCH',
        'itchLocale.menuBar.projectIsSaving': 'Saving...',
        'itchLocale.menuBar.projectNotSaved': 'Not Saved',
        'itchLocale.menuBar.projectSaved': 'Saved'
    },
    'uk': {
        'itchLocale.alerts.remixing': 'Remixing...',
        'itchLocale.alerts.remixed': 'Successfully remixed.',
        'itchLocale.alerts.savingOriginal': 'Save original project...',
        'itchLocale.alerts.coping': 'Copying...',
        'itchLocale.alerts.successfullyCopied': 'Successfully copied.',
        'itchLocale.cards.lessons': 'Lessons',
        'itchLocale.cards.directions': 'View directions',
        'itchLocale.cards.getAssigment': 'Get Assignment',
        'itchLocale.cards.noLessons': 'No Lessons Available',
        'itchLocale.menuBar.itchLessons': 'Lessons from iTCH',
        'itchLocale.menuBar.projectIsSaving': 'Saving...',
        'itchLocale.menuBar.projectNotSaved': 'Not Saved',
        'itchLocale.menuBar.projectSaved': 'Saved'
    },
    'zh-cn': {
        'itchLocale.alerts.remixing': 'Remixing...',
        'itchLocale.alerts.remixed': 'Successfully remixed.',
        'itchLocale.alerts.savingOriginal': 'Save original project...',
        'itchLocale.alerts.coping': 'Copying...',
        'itchLocale.alerts.successfullyCopied': 'Successfully copied.',
        'itchLocale.cards.lessons': 'Lessons',
        'itchLocale.cards.directions': 'View directions',
        'itchLocale.cards.getAssigment': 'Get Assignment',
        'itchLocale.cards.noLessons': 'No Lessons Available',
        'itchLocale.menuBar.itchLessons': 'Lessons from iTCH',
        'itchLocale.menuBar.projectIsSaving': 'Saving...',
        'itchLocale.menuBar.projectNotSaved': 'Not Saved',
        'itchLocale.menuBar.projectSaved': 'Saved'
    },
    'zh-tw': {
        'itchLocale.alerts.remixing': 'Remixing...',
        'itchLocale.alerts.remixed': 'Successfully remixed.',
        'itchLocale.alerts.savingOriginal': 'Save original project...',
        'itchLocale.alerts.coping': 'Copying...',
        'itchLocale.alerts.successfullyCopied': 'Successfully copied.',
        'itchLocale.cards.lessons': 'Lessons',
        'itchLocale.cards.directions': 'View directions',
        'itchLocale.cards.getAssigment': 'Get Assignment',
        'itchLocale.cards.noLessons': 'No Lessons Available',
        'itchLocale.menuBar.itchLessons': 'Lessons from iTCH',
        'itchLocale.menuBar.projectIsSaving': 'Saving...',
        'itchLocale.menuBar.projectNotSaved': 'Not Saved',
        'itchLocale.menuBar.projectSaved': 'Saved'
    }
};
